// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col min-h-screen\"><div class=\"flex flex-col items-center flex-1 px-8 pt-8 mb-4\"><h1 class=\"script text-6xl xl:text-8xl\">The Drewzers</h1><h2 class=\"script text-4xl xl:text-6xl\">are getting married</h2><span class=\"text-xs\">&lpar;yes, Andrew chose to call us \"The Drewzers\"&rpar;</span></div><nav class=\"flex justify-center mb-4\"><ul class=\"list-none flex flex-row gap-4\"><li><a class=\"text-sm\" href=\"#our-story\">Our story</a></li><li><a class=\"text-sm\" href=\"#event-details\">Event details</a></li><li><a class=\"text-sm\" href=\"#rsvp\">RSVP</a></li><li><a class=\"text-sm\" href=\"#contact\">Contact</a></li></ul></nav><div class=\"flex justify-center\"><img src=\"/static/images/couple_cover_250x500.png\" class=\"h-[500px] w-[250px]\"></div><section id=\"our-story\"><h3 class=\"script text-2xl xl:text-4xl\">Our story</h3><p class=\"mb-8\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p class=\"mb-8\">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p class=\"mb-8\">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p></section><section id=\"event-details\"><h3 class=\"script text-2xl xl:text-4xl\">Details</h3></section><section id=\"rsvp\"><h3 class=\"script text-2xl xl:text-4xl\">RSVP</h3></section><section id=\"contact\"><h3 class=\"script text-2xl xl:text-4xl\">Contact</h3></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
